name : Python Energy Workflow

on: 
  push:
    branches:
      - main
      - test_luni

jobs:
  optimize-python-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt  

    - name: Run script
      run: python feature1/autocomp.py

    - name: Commit and push if it's a success
      run: |
        git config --global user.name 'Energy Bot'
        git config --global user.email 'EBOT@gmail.com'

        # Check for changes
        if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
        else
            git stash
            git checkout energy || git checkout -b energy
            git stash apply
            git pull origin energy --rebase || true
            git add .
            git commit -m "Optimized code"
            git push origin energy
        fi
      if: ${{ success() }}
