    - name: Commit and push if it's a success
      run: |
        git config --global user.name 'Energy Bot'
        git config --global user.email 'EBOT@gmail.com'
        git stash
        git checkout energy || git checkout -b energy
        git stash apply
        git pull origin energy --rebase || true
        git add .
        git commit -m "Optimized code"
        git push origin energy
      if: ${{ success() }}